import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '4rem',
        xl: '5rem',
        '2xl': '6rem',
      },
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['var(--font-display)', 'Instrument Sans', 'var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-1': ['72px', { lineHeight: '0.98', letterSpacing: '-0.035em', fontWeight: '600' }],
        'display-2': ['56px', { lineHeight: '1.0', letterSpacing: '-0.032em', fontWeight: '600' }],
        'h1': ['40px', { lineHeight: '1.08', letterSpacing: '-0.028em', fontWeight: '600' }],
        'h2': ['28px', { lineHeight: '1.18', letterSpacing: '-0.022em', fontWeight: '600' }],
        'h3': ['21px', { lineHeight: '1.28', letterSpacing: '-0.016em', fontWeight: '600' }],
        'title': ['17px', { lineHeight: '1.4', letterSpacing: '-0.011em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '1.6', letterSpacing: '-0.004em', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.55', letterSpacing: '0', fontWeight: '400' }],
        'caption': ['13px', { lineHeight: '1.45', letterSpacing: '0', fontWeight: '400' }],
        'eyebrow': ['11px', { lineHeight: '1.35', letterSpacing: '0.06em', fontWeight: '600' }],
        'metric': ['38px', { lineHeight: '1.0', letterSpacing: '-0.03em', fontWeight: '600' }],
        'metric-lg': ['52px', { lineHeight: '0.98', letterSpacing: '-0.034em', fontWeight: '600' }],
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        notion: {
          primary: 'hsl(var(--notion-primary))',
          'primary-active': 'hsl(var(--notion-primary-active))',
          'on-primary': 'hsl(var(--notion-on-primary))',
          secondary: 'hsl(var(--notion-secondary))',
          canvas: 'hsl(var(--notion-canvas))',
          'canvas-soft': 'hsl(var(--notion-canvas-soft))',
          surface: 'hsl(var(--notion-surface))',
          sunken: 'hsl(var(--notion-sunken))',
          ink: 'hsl(var(--notion-ink))',
          'ink-secondary': 'hsl(var(--notion-ink-secondary))',
          'ink-muted': 'hsl(var(--notion-ink-muted))',
          'ink-faint': 'hsl(var(--notion-ink-faint))',
          hairline: 'hsl(var(--notion-hairline))',
          accent: {
            sky: 'hsl(var(--notion-accent-sky))',
            purple: 'hsl(var(--notion-accent-purple))',
            'purple-deep': 'hsl(var(--notion-accent-purple-deep))',
            pink: 'hsl(var(--notion-accent-pink))',
            orange: 'hsl(var(--notion-accent-orange))',
            'orange-deep': 'hsl(var(--notion-accent-orange-deep))',
            teal: 'hsl(var(--notion-accent-teal))',
            green: 'hsl(var(--notion-accent-green))',
            brown: 'hsl(var(--notion-accent-brown))',
          }
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        data: {
          1: 'hsl(var(--data-1))',
          2: 'hsl(var(--data-2))',
          3: 'hsl(var(--data-3))',
          4: 'hsl(var(--data-4))',
          5: 'hsl(var(--data-5))',
          positive: 'hsl(var(--data-positive))',
          negative: 'hsl(var(--data-negative))',
          'positive-soft': 'hsl(var(--data-positive-soft))',
          'negative-soft': 'hsl(var(--data-negative-soft))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        xs: '6px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '30px',
        full: '9999px',
      },
      boxShadow: {
        'notion-soft': 'rgba(28,25,23,0.02) 0 1px 2px, rgba(28,25,23,0.02) 0 3px 6px, rgba(28,25,23,0.03) 0 8px 18px -6px',
        'notion-elevated': 'rgba(28,25,23,0.02) 0 1px 2px, rgba(28,25,23,0.03) 0 4px 10px -2px, rgba(28,25,23,0.05) 0 14px 32px -10px, rgba(28,25,23,0.04) 0 32px 64px -24px',
        glow: '0 0 40px -10px var(--tw-shadow-color)',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '28px',
        xxl: '32px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
